Update CI to throw error on cargo test failure

diff --git a/.github/workflows/test-scout.yml b/.github/workflows/test-scout.yml
--- a/.github/workflows/test-scout.yml
+++ b/.github/workflows/test-scout.yml
@@ -62,6 +62,9 @@ jobs:
         run: |
           if cargo test --all --all-features; then
             echo "${{ runner.os }}_status=success" >> $GITHUB_OUTPUT
+          else
+            echo "${{ runner.os }}_status=failure" >> $GITHUB_OUTPUT
+            exit 1
           fi
 
   comment-on-pr:
